CREATE SCHEMA `jujube` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
use `jujube`;

CREATE TABLE `user` (
  `uid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uname` VARCHAR(20) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `uid_UNIQUE` (`uid` ASC),
  UNIQUE INDEX `uname_UNIQUE` (`uname` ASC));

  CREATE TABLE `jujube`.`userBase` (
  `uid` INT UNSIGNED NOT NULL,
  `gender` CHAR(1) NULL DEFAULT 0,
  `money` INT UNSIGNED NULL DEFAULT 0,
  `exp` INT UNSIGNED NULL DEFAULT 0,
  `vip` TINYINT(4) UNSIGNED NULL DEFAULT 0,
  `nickname` VARCHAR(18) NULL DEFAULT 'anonymous',
  `iconUrl` VARCHAR(100) NULL DEFAULT '',
  UNIQUE INDEX `uid_UNIQUE` (`uid` ASC),
  PRIMARY KEY (`uid`));


