CREATE SCHEMA `jujube` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
use `jujube`;

CREATE TABLE `user` (
  `uid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uname` VARCHAR(20) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `uid_UNIQUE` (`uid` ASC),
  UNIQUE INDEX `uname_UNIQUE` (`uname` ASC));

CREATE TABLE `jujube`.`userBase` (
  `uid` INT UNSIGNED NOT NULL,
  `gender` CHAR(1) NULL DEFAULT 0,
  `money` INT UNSIGNED NULL DEFAULT 0,
  `exp` INT UNSIGNED NULL DEFAULT 0,
  `vip` TINYINT(4) UNSIGNED NULL DEFAULT 0,
  `nickname` VARCHAR(18) NULL DEFAULT 'anonymous',
  `iconUrl` VARCHAR(100) NULL DEFAULT '',
  UNIQUE INDEX `uid_UNIQUE` (`uid` ASC),
  PRIMARY KEY (`uid`));

CREATE TABLE `jujube`.`friendRequest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `srcUid` INT UNSIGNED NOT NULL,
  `destUid` INT UNSIGNED NOT NULL,
  `timestamp` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idfriendRequest_UNIQUE` (`id` ASC));

CREATE TABLE `jujube`.`friend` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uid1` INT UNSIGNED NOT NULL,
  `uid2` INT UNSIGNED NOT NULL,
  `remark1` VARCHAR(30) NULL,
  `remark2` VARCHAR(30) NULL,
  `timestamp` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


CREATE TABLE `jujube`.`message` (
  `msgId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` TINYINT(8) UNSIGNED NOT NULL,
  `status` BIT(1) NOT NULL,
  `srcUid` INT UNSIGNED NOT NULL,
  `destUid` INT UNSIGNED NOT NULL,
  `sentTime` INT UNSIGNED NOT NULL,
  `msg` TEXT(1024) NOT NULL,
  PRIMARY KEY (`msgId`),
  UNIQUE INDEX `msgId_UNIQUE` (`msgId` ASC));


